### ISSUE TITLE
Port 445 can't be used if Honeypot is enabled in Firewall settings

### ISSUE THREAD

**Issue by OfficialHoSay** [thealpa/UDMPRO-samba#1]
The Internal Honeypot uses port 445, which is used by the samba container.

I don't think this can be easily solved, but if that's the case, maybe it's a good heads up to have in the README file to avoid someone else having to troubleshoot this.

**Comment by thealpa** [comment]
Thank you! I agree, this is a good heads up. Changing the port to any other than the default SMB port would probably also lead to confusion.
